### ISSUE TITLE
NuGet packages are not published for release/2.0.0 branch

### ISSUE THREAD

**Issue by hqueue** [tizendotnet/netcore-jenkins#11]
Even after we pushed nuget packages to the myget from Jenkins CI on AWS, pushed packages are not found at https://tizen.myget.org/gallery/dotnet-core

**Comment by hqueue** [comment]
![image](https://user-images.githubusercontent.com/9247907/31424164-bb43a1b6-ae93-11e7-9e1c-278720d8f5c0.png)

**Comment by hqueue** [comment]
Found that newly  pushed 2.0.2 NuGet packages are deleted by retention rule.

**Comment by hqueue** [comment]
Current retention rule for  https://tizen.myget.org/gallery/dotnet-core

200 packages are kept for each stable branch and prerelease branch.

![image](https://user-images.githubusercontent.com/9247907/31424192-e3c953a6-ae93-11e7-9087-da18eafb45c9.png)

**Comment by hqueue** [comment]
Therefore I temporarily remove limitation (blank).

We should discuss rule for retention or policy how many packages we should maintain.
(1) Retention rule
(2) How to apply retention rule (e.g. webhook)

**Comment by hseok-oh** [comment]
- save version for each package

1. stable version: save all
2. prerelease version: defined no. of new packages
2.1 master (previewX)
2.2 prerelease (servicing) for each release branch: Now 2.0.0 for armel

- remove needless packages

**Comment by hqueue** [comment]
There is a hard limitation of the storage on myget server in our account and only 13% is free by now.

So we have to decide and apply retention rule ASAP.

**Comment by hqueue** [comment]
@hseok-oh I also agree on your suggestion with addition of minor detail as below, because there can be several versions from single branch.


- save version for each package
1. stable version: save all
2. prerelease version: defined # of new packages
```
   for each version in [ 2.0.0, 2.0.1, 2.0.2, 2.1.0 and any further version ]
       keep only specific # of packages
```
- remove needless packages



/cc: @ragmani

**Comment by hseok-oh** [comment]
@hqueue Should we save in each storage for 2.0.0, 2.0.1, and 2.0.2? I think we can keep using major and minor version number (2.0.X, 2.1.X).

**Comment by ragmani** [comment]
This is feedback from the Myget Support team.
https://myget.freshdesk.com/helpdesk/tickets/1574
https://myget.freshdesk.com/helpdesk/tickets/1575

**Comment by hqueue** [comment]
@ragmani Thank you for opening tickets. And it seems that we got **expected** answers we already knew.

**Comment by hqueue** [comment]
Because there is a security concerns, let's discuss this issue in private space.

**Comment by ragmani** [comment]
This is PR for custom retention rule. https://github.com/tizendotnet/netcore-jenkins/pull/15

**Comment by hqueue** [comment]
Discussion was done in private repo.

**Comment by hqueue** [comment]
Thanks @ragmani 

Close this issue as issue in  private repo is closed.
